version: '3'

services:
    jekyll:
        image: jekyll/jekyll
        container_name: joonghyunlee.github.io
        environment:
            - JEKYLL_ENV=docker
        command: jekyll serve --watch --force_polling --verbose
        ports:
            - 4000:4000
        volumes:
            - ../:/srv/jekyll
