version: '3'

services:
    jekyll:
        image: jekyll/jekyll
        container_name: joonghyunlee.github.io
        environment:
            - JEKYLL_ENV=docker
        command: jekyll serve --force_polling --livereload
        ports:
            - 4000:4000
            - 35729:35729
        volumes:
            - ../:/srv/jekyll
